### ISSUE TITLE
small fix and other languages

### ISSUE THREAD

**Issue by dusttier** [CodeZombie/TypeRip#7] opened 2018-10-18 14:39 UTC
Hello comrade!
I think better use json.family.fonts.length instead json.family.total_font_count 
Because some fonts will return errors - https://fonts.adobe.com/fonts/franklin-gothic-urw
May be you have solution - how to grab all characters for all languages?
I cant undestand you last language fix...((
Thank you for awesome app.

**Comment by CodeZombie** [comment] 2019-10-22 06:12
Good catch, that works perfectly. Thanks!

And which fonts are you trying to get all characters for?

**Comment by mimonaut** [comment] 2019-11-18 21:15
I have also trouble to get "pro" version of fonts.. It takes only STD (basic) charset, so a bit confusing.. I am from czech republic, so I need chars like ěščřřžžýáí.. If I wrote those letters to preview window on adobe page, it loads a while and then it shows example correctly.. But downloaded font from typerip have no "pro" characters.. is there a way to get that full fonts please? I tried American typewriter for examle..

**Comment by egeesin** [comment] 2019-12-02 16:42
Can confirm, no Turkish characters (ğşıİ) as well.

**Comment by fontmaster727** [comment] 2020-05-08 18:01
I'm trying to get VDL-Logona since the new Club House Games uses it, but some of the Japanese letters don't appear.

**Comment by shitrip** [comment] 2020-05-18 14:07
confirmed to fail with ň - Unicode Character 'LATIN SMALL LETTER N WITH CARON' (U+0148)

**Comment by darvell** [comment] 2020-08-02 02:34
Alternate characters are in a very modified and odd CFF version called 'Adobe Blank' if I understand correctly (which would explain why the header is a CFF but at version 0). I would believe certain parts of the codepages have their own files hence why there are multiple requests when on the site.

**Comment by darvell** [comment] 2020-08-03 20:45
There's a trick to this apparently. Get the WOFF2 versions. Iterate the subset_id until you're returning failures. There is a scenario if you make enough wrong calls or too many within a minute you'll get your ass kicked and blocked for 5 minutes. But the WOFF2 ones can be merged together with fontmerge from pythons fonttools. Don't know if there's a node equivalent but it seems to fix things...

Hopefully that helps a little, I'd like to submit a bit more help but I honestly just don't have the time. Just maybe this can help fix the issue of alternate languages.

**Comment by gingerbeardman** [comment] 2020-11-04 23:50
> I'm trying to get VDL-Logona since the new Club House Games uses it, but some of the Japanese letters don't appear.

Also with VDL-LogoJrBlack https://fonts.adobe.com/fonts/vdl-logojrblack

at least these characters are missing: リド

**Comment by Ynng** [comment] 2021-05-04 06:26
> > I'm trying to get VDL-Logona since the new Club House Games uses it, but some of the Japanese letters don't appear.
> 
> Also with VDL-LogoJrBlack `vdl-logojrblack`
> 
> at least these characters are missing: リド

I was just trying to get [VDL-GigaMaruJr](https://fonts.adobe.com/fonts/vdl-gigamarujr) and had similar problems.

I think this is due to typekit's dynamic subsetting. Both the request and response are not in any standard formats so this probably won't be an easy problem to tackle.

Here are a few random links I've found on the topic:
* https://iyn.me/i/post-44.html
* https://blog.typekit.com/2015/06/15/announcing-east-asian-web-font-support/
* https://helpx.adobe.com/fonts/user-guide.html/fonts/using/dynamic-subsetting.ug.html

**Comment by CodeZombie** [comment] 2021-05-06 04:06
I believe the latest commit has fixed this issue. **The tool is now able to grab what I believe is the complete character set for any font.** 
Thankfully this didnt require trying to mess around with Adobe's dynamic subsetting. The undocumented API I'm using to pull fonts from includes a "unicode" parameter which attempts to include glyphs from within some kind of range depending on the value.

One of Adobe's standard fonts that they use on every page is requested using this api, and includes `?unicode=AAAAAQAAAAEAAAAB` in the URL. I believe this asks the server for every character in the font to be served as opposed to a basic latin subset. I put this string into the font download URL within the tool, got rid of the primer, and now its grabbing full fonts.

I've tested it on all the fonts mentioned in this thread and can't find any missing glyphs.

As always, please let me know if something isn't working.

**Closed by CodeZombie** 2021-05-06 04:06 UTC
