### ISSUE TITLE
@font-face generators not working with fonts

### ISSUE THREAD

**Issue by dusttier** [CodeZombie/TypeRip#34] opened 2023-06-12 21:51 UTC
Unfortunately, @font-face generators(transfonter.org) not cant` convert fonts(
"Font file is corrupted"

**Comment by CodeZombie** [comment] 2024-01-08 05:42
Closing because the latest TypeRip update appears to have fixed any corrupt font issues, and I'm not able to reproduce this anymore.
Please open a new Issue if this happens again persists!

**Closed by CodeZombie** 2024-01-08 05:42 UTC
