### ISSUE TITLE
Not working ERROR 404

### ISSUE THREAD

**Issue by DesolateHawk1** [CodeZombie/TypeRip#52] opened 2024-12-13 15:33 UTC
Do you think this is fixable? Thanks, mate!

![image](https://github.com/user-attachments/assets/64114c0a-ea30-4c6c-ab8e-d446bd875b6f)

**Comment by CodeZombie** [comment] 2024-12-13 22:09
Duplicate of #51 , which _should_ be resolved now. 
Take a look at my comment on that Issue and let me know if anything still isn't working :)

**Closed by CodeZombie** 2024-12-13 22:09 UTC
